//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McCulloch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class McCullochMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal McCullochMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("McCulloch.McCullochMessages", typeof(McCullochMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be an empty array..
        /// </summary>
        internal static string ArgumentException_EmptyArray {
            get {
                return ResourceManager.GetString("ArgumentException_EmptyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be an empty string..
        /// </summary>
        internal static string ArgumentException_StringEmpty {
            get {
                return ResourceManager.GetString("ArgumentException_StringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be in the range [0, {0}]..
        /// </summary>
        internal static string ArgumentOutOfRangeException_InvalidIndex {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should not be negative..
        /// </summary>
        internal static string ArgumentOutOfRangeException_IsNegative {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_IsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be positive..
        /// </summary>
        internal static string ArgumentOutOfRangeException_IsNotPositive {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_IsNotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a number..
        /// </summary>
        internal static string ArgumentOutOfRangeException_NaN {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_NaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation {0} could not be excucuted as the dimensions of the matrices don&apos;t match..
        /// </summary>
        internal static string DimensionMismatchException_ForOperation {
            get {
                return ResourceManager.GetString("DimensionMismatchException_ForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} size does not match the {1} size..
        /// </summary>
        internal static string DimensionMismatchException_NeuralNetwork {
            get {
                return ResourceManager.GetString("DimensionMismatchException_NeuralNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0}.{1} contains both an input and output attribute..
        /// </summary>
        internal static string InvalidModelException_InputAndOutput {
            get {
                return ResourceManager.GetString("InvalidModelException_InputAndOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0}.{1} of the type {2} is not supported..
        /// </summary>
        internal static string InvalidModelException_TypeOfPropertyNotSupported {
            get {
                return ResourceManager.GetString("InvalidModelException_TypeOfPropertyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not an enum..
        /// </summary>
        internal static string NotSupportedException_NotAnEnum {
            get {
                return ResourceManager.GetString("NotSupportedException_NotAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is not defined for this Category..
        /// </summary>
        internal static string NotSupportedException_ValueNotInCategory {
            get {
                return ResourceManager.GetString("NotSupportedException_ValueNotInCategory", resourceCulture);
            }
        }
    }
}
